[package]
name = "n_times_faster_than_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
rand = "0.8.5"
seq-macro = "0.3.4"

[[bench]]
name = "benchmark"
harness = false
